apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: key-auth
    konghq.com/strip-path: "false"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"konghq.com/strip-path":"false"},"name":"litellm","namespace":"tenant-a"},"spec":{"ingressClassName":"kong","rules":[{"host":"a.litellm.local","http":{"paths":[{"backend":{"service":{"name":"litellm","port":{"number":4000}}},"path":"/","pathType":"Prefix"}]}}]}}
  creationTimestamp: "2026-02-19T03:34:08Z"
  generation: 1
  name: litellm
  namespace: tenant-a
  resourceVersion: "68037"
  uid: 14d7cbe6-1273-4b8d-a0af-6be47045810e
spec:
  ingressClassName: kong
  rules:
  - host: a.litellm.local
    http:
      paths:
      - backend:
          service:
            name: litellm
            port:
              number: 4000
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.96.39.192
